# .github/workflows/rewards_automation.yml

name: Daily Microsoft Rewards Automation

on:
  schedule:
    # This cron job runs every 30 minutes between 7:30 AM and 12:30 PM UTC.
    # This corresponds to roughly 1:00 PM to 6:00 PM in the Indian Standard Time (IST) zone.
    # The random delay in the steps makes the exact start time unpredictable.
    - cron: "*/30 7-12 * * *"

  # This allows you to run the workflow manually from the GitHub Actions tab
  workflow_dispatch:

jobs:
  run-rewards-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Introduce a random delay
        run: |
          DELAY=$((RANDOM % 1800))
          echo "Delaying the start for ${DELAY} seconds to make it random..."
          sleep $DELAY
        shell: bash

      - name: 3. Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 4. Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

        # --- यहाँ बदलाव किया गया है ---
      - name: 5. Run the Rewards Bot Script
        env:
          # यह सीक्रेट को एक एनवायरनमेंट वेरिएबल में सुरक्षित रूप से लोड करता है
          BING_COOKIES_JSON: ${{ secrets.BING_COOKIES }}
        run: |
          # अब हम एनवायरनमेंट वेरिएबल से सीधे फ़ाइल बनाते हैं
          echo "$BING_COOKIES_JSON" > bing_cookies.json
          python rewards_bot.py

      - name: 6. Upload Proof Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: login-proof
          path: login_status_proof.png
